version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.service2
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/fullstack
    networks:
      - laravel

  backend:
    build:
      context: .
      dockerfile: Dockerfile.service1
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - .:/var/www/fullstack
    ports:
      - '9000:9000'
    networks:
      - laravel
    entrypoint: ['/var/www/fullstack/entrypoint.sh']

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

networks:
  laravel:
    driver: bridge
