name: Build and Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Deploy to Azure VM
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSHKEY: ${{ secrets.SSHKEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          sshpass -p "$SSHKEY" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull $DOCKER_USERNAME/my-laravel-app:latest
            docker stop my-laravel-app || true
            docker rm my-laravel-app || true
            docker run -d -p 80:80 --name my-laravel-app $DOCKER_USERNAME/my-laravel-app:latest
          EOF
