name: Build and Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: docker-compose -f docker-compose.yml build && docker-compose -f docker-compose.yml push

      # - name: Build and push backend image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: Dockerfile.service1
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/my-laravel-backend:latest

      # - name: Build and push frontend image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: Dockerfile.service2
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/my-laravel-frontend:latest

      # - name: Build and push nginx image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     file: Dockerfile.nginx
      #     tags: ${{ secrets.DOCKER_USERNAME }}/my-laravel-nginx:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:latest
            docker container rm -f my-laravel-app || true
            docker run -d --name my-laravel-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:latest && docker exec my-laravel-app nginx
