name: Build and Deploy Laravel Application

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: ${{ secrets.DB_HOST }}/my-laravel-app:latest
          build-args: |
            DB_HOST=${{  secrets.DB_HOST }}

      - name: SCP files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: 'nginx/,docker-compose.yml'

      - name: deploy to server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export DB_HOST=${{ secrets.DB_HOST }}
            CI=true docker login -u ${{  secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            CI=true docker-compose down
            CI=true docker-compose build --no-cache
            CI=true docker image prune -a -f
            CI=true docker-compose up -d --force-recreate

  # automerge:
  #   runs-on: ubuntu-latest
  #   needs: [build_and_deploy]
  #   steps:
  #     - id: automerge
  #       name: automerge
  #       uses: 'pascalgn/automerge-action@v0.16.3'
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         MERGE_LABELS: ''
